### ISSUE TITLE
Please add uv-max

### ISSUE THREAD

**Issue by Beejeedeb** [tim-hellhake/openuv-adapter#1]
Hi is it possible to also include uv_max in the thing?

(max UV Index for the day (at solar noon)) 

Would be great if I could put a colorsmart light in my bathroom that shows me in the morning with a color if I should put on sunscreen or take it with me for the day. :-)

**Comment by tim-hellhake** [comment]
Will be available when https://github.com/mozilla-iot/addon-list/pull/335 is merged

**Comment by tim-hellhake** [comment]
Sorry, i missed your question: of course! :-)
