### ISSUE TITLE
Release 0.2.0 - ozone- and uv time dont fit - add uv level text

### ISSUE THREAD

**Issue by Beejeedeb** [tim-hellhake/openuv-adapter#2]
![openuv time circle](https://user-images.githubusercontent.com/51539492/60338052-1c011f80-99a5-11e9-8019-9c2f0273ac19.PNG)

This is very good information I can use in my rules, however the ozon- and uv time could be shorter they don't fit very well in the circle. Maybe removing the date part is a solution. Don't use the date in my rules. It's also making a rule based on the time a bit easier.

Is it also possible to include the uv- and uv level text in a circle (and add it to the rules).
![uv level](https://user-images.githubusercontent.com/51539492/60338653-cfb6df00-99a6-11e9-9ffd-103d2e6fcc88.PNG)

Ozon level is in du (Dobson Units) maybe nice to include it as an unit in your code.

I appreciate the work you are putting in the Mozilla-IOT gateway it makes it much more usable for me :-)

**Comment by tim-hellhake** [comment]
>Maybe removing the date part is a solution.

I already extracted the time from the datetime, but it seems I accidentally reverted the changes.

>Is it also possible to include the uv- and uv level text

Good idea!
I'll add an `UV Level Name` property.
Anything else I should add?

>in a circle

Do you mean in the preview of the thing?
That would require changes in the gateway.

>Ozon level is in du (Dobson Units) maybe nice to include it as an unit in your code.

Thanks for the hint, I'll add that.

>I appreciate the work you are putting in the Mozilla-IOT gateway it makes it much more usable for me :-)

Thank you very much.
Nice to hear that my work is appreciated :-)

**Comment by Beejeedeb** [comment]
nope sorry for the confusion, I mean uv- and uv max in their own circle or in the circle (what are the circles called in the thing, blobs?) where the uv- and uv max numbers are.

**Comment by tim-hellhake** [comment]
Maybe property bubbles? :thinking:
Anyway, this shouldn't be a problem.
However, displaying a value in the thing bubble would require a new property type.
And then the question would be: which property? `uv` or `uv_max`?

**Comment by Beejeedeb** [comment]
Good question, imo displaying dynamic information is more interesting. uv_max is quite static for a day. I am for displaying dynamic uv information just like for example the dynamic temperature displayed by temperature sensors.

**Comment by tim-hellhake** [comment]
I prepared a new release: https://github.com/tim-hellhake/openuv-adapter/releases/tag/0.3.0

**Comment by tim-hellhake** [comment]
PR is also on the way: https://github.com/mozilla-iot/addon-list/pull/337

**Comment by Beejeedeb** [comment]
Great! Will test it today. 

I see that you're also responsible for Google Home Text to Speech add on. Will also bother you over there with some recommendations for improvements 😊

**Comment by Beejeedeb** [comment]
Nice!! Looks good.

![openuv](https://user-images.githubusercontent.com/51539492/60395685-c3f22680-9b26-11e9-83c6-12250cbe4fc3.PNG)

Couple of things I encountered while testing it:

-  I am not sure if max UV is refreshed, looks same as yesterday. Will make a log and check it tomorrow.

- Instead of UV text and Max UV text you coud use UV level and Max UV level.

- Is for the Ozone value one digit after the decimal point not enough? Looks imo better and the other decimals aren't probably used.

- Ozone time and UV time, I am not sure if seconds and milliseconds are necessary.

- Ozon time and UV time are refresh times, Ozon refresh time and UV refresh time?

- Is it possible to make a drop down list for the max- and uv text in the rule. It isn't clear what one should use here.

![openuv rule](https://user-images.githubusercontent.com/51539492/60395847-17657400-9b29-11e9-9ba4-13b285203bb9.PNG)

- In rule it isn't clear what time format to fill in for UV -and Ozone time. Are UV -and Ozone time necessary in making a rule with OpenUV? I filled in a random time. 

![openuv rule 2](https://user-images.githubusercontent.com/51539492/60395966-c3f42580-9b2a-11e9-980d-86d28380dac8.PNG)

- "OpenUV - Clear sky UV index" That's the name I  would give it because now its's clear that the index is for clear skies. Only a suggestion :-)

That's it, those are the things I saw. But for me it is already very usable as it is.

**Comment by tim-hellhake** [comment]
> Is for the Ozone value one digit after the decimal point not enough? Looks imo better and the other decimals aren't probably used.

The precision is controlled by the gateway.
However, there is a PR which allows the addon to specify the desired precision: https://github.com/mozilla-iot/gateway/pull/1971
It's merged but I think it's not included in the latest gateway release.

**Comment by tim-hellhake** [comment]
It doesn't seem to work, though.
https://github.com/mozilla-iot/gateway/issues/1980

**Comment by tim-hellhake** [comment]
>Is it possible to make a drop down list for the max- and uv text in the rule. It isn't clear what one should use here.

That should work now

**Comment by tim-hellhake** [comment]
>Ozone time and UV time, I am not sure if seconds and milliseconds are necessary.

Refresh now shows only hours and minutes.
Be aware it's local time now.

**Comment by Beejeedeb** [comment]
Local time is even better than UTC, forgot to mention this. 

I am in another timezone I will go to bed now and install the latest version with all the changes tomorrow.

**Comment by Beejeedeb** [comment]
You did an amazing job. Thanks. 

Max UV refreshed this morning.

Everything works as far as I can see . Only thing is the precision but that is out of your control.

![openuv3](https://user-images.githubusercontent.com/51539492/60433075-2c630580-9c04-11e9-8d21-5a845eb7536c.PNG)

**Comment by tim-hellhake** [comment]
> In rule it isn't clear what time format to fill in for UV -and Ozone time. Are UV -and Ozone time necessary in making a rule with OpenUV? I filled in a random time.

I would leave it empty.
The rule engine should ignore it.

**Comment by tim-hellhake** [comment]
From what I can see, all issues are resolved now.
I'll prepare a new release and close this issue.

**Comment by tim-hellhake** [comment]
I just noticed that the precision issue was fixed.
Seems to work now.

![precision-fixed](https://user-images.githubusercontent.com/17127122/60469393-bfc82500-9c5c-11e9-875a-a8749a1b3821.png)

**Comment by tim-hellhake** [comment]
PR is open
https://github.com/mozilla-iot/addon-list/pull/338
